model:
  default:
    temperature: 0.7
    max_tokens: 2000
  openai:
    name: "gpt-3.5-turbo"
  chatglm:
    url: "http://192.168.0.107:5000"
    max_tokens: 4000
model_provider: "chatglm"
input_file: "../tests/test.pdf"
output_file_format: "markdown"
source_language: "English"
target_language: "Chinese"
pages: 2